apiVersion: k3d.io/v1alpha4
kind: Simple
metadata:
  name: openfaas
servers: 1
agents: 2
registries:
  create:
    name: registry.localhost
    host: "0.0.0.0"
    hostPort: "5000"
  use: []
ports:
  - port: 27017:27017
    nodeFilters:
      - loadbalancer
  - port: 8080:8080
    nodeFilters:
      - loadbalancer
  - port: 9999:9999
    nodeFilters:
      - loadbalancer
options:
  k3d:
    wait: true
  kubeconfig:
    switchCurrentContext: true
    updateDefaultKubeconfig: true
