{{ range .Values.services }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .name }}
  annotations: {{ .annotations | toYaml | nindent 4 }}
spec:
  ports:
    - port: 8080
      name: http
  selector:
    app: gateway
  type: ClusterIP
{{- end }}
